apiVersion: v1
kind: Namespace
metadata:
  name: cost-sample
  labels:
    team: payments
    env: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: cost-sample
  labels:
    app: cart
    service: cart
    team: payments
    env: dev
    cost_center: cc-1001
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
        service: cart
        team: payments
        env: dev
        cost_center: cc-1001
    spec:
      containers:
        - name: cart
          image: ghcr.io/shipwright-io/sample-go-http:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 150m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          env:
            - name: SAMPLE_LATENCY_MS
              value: "25"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: cost-sample
spec:
  selector:
    app: cart
  ports:
    - port: 80
      targetPort: 8080
