replicaCount: 1

image:
  repository: ghcr.io/clustercost/clustercost-agent-k8s
  tag: "v0.1.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

affinity: {}

tolerations: []

extraEnv: []
extraArgs: []
podAnnotations: {}

pricing:
  provider: aws
  region: us-east-1
  cpuHourPrice: 0.046
  memoryGibHourPrice: 0.005

scrapeIntervalSeconds: 30
logLevel: info
clusterName: kubernetes

metricsServiceMonitor:
  enabled: false
  namespace: ""
  interval: 30s

rbac:
  create: true
